// NærTur — i18n strings + mock hike data for Møre og Romsdal

window.I18N = {
  no: {
    appName: 'NærTur',
    tagline: 'Én tapp. Få en nær tur som passer i dag.',
    welcomeSub: 'Vi finner én tur for deg — basert på vær, sesong og hva du har lyst på i dag.',
    useLocation: 'Bruk min posisjon',
    chooseTown: 'Velg sted',
    locationAround: 'Søker rundt',
    near: 'nær',
    edit: 'Endre',
    filters: 'Filtre',
    difficulty: 'Vanskelighet',
    easy: 'Enkel',
    medium: 'Medium',
    hard: 'Krevende',
    length: 'Lengde',
    under5: 'Under 5 km',
    fiveTen: '5–10 km',
    tenPlus: '10+ km',
    transport: 'Transport',
    car: 'Bil',
    publicTransport: 'Kollektiv',
    walk: 'Til fots',
    maxTravel: 'Maks reisetid',
    minutes: 'min',
    preferences: 'Tema',
    avoid: 'Unngå',
    findHike: 'Finn tur',
    finding: 'Finner din tur',
    findingSub: 'Sjekker vær, sesong og reisetid',
    recommended: 'Anbefalt i dag',
    checkConditions: 'Sjekk forhold',
    notRecommended: 'Ikke anbefalt nå',
    distance: 'Lengde',
    ascent: 'Stigning',
    duration: 'Tid',
    travel: 'Reisetid',
    whyThis: 'Hvorfor denne turen',
    startHike: 'Start tur',
    anotherOne: 'Velg en annen',
    notMine: 'Ikke min tur',
    safetyNote: 'Anbefalt basert på tilgjengelige data. Sjekk alltid lokale forhold.',
    source: 'Kilde',
    openInMaps: 'Åpne i kart',
    description: 'Om turen',
    trailhead: 'Startpunkt',
    parking: 'Parkering',
    season: 'Sesong',
    monthsOpen: 'Sesong',
    backToResult: 'Tilbake',
    rejectedTitle: 'Forsto. Finner noe annet.',
    rejectedSub: 'Vi prøver en ny tur basert på det du har sagt nei til.',
    locating: 'Finner posisjon',
    locOk: 'Posisjon funnet',
    weatherOk: 'God værmelding',
    seasonOk: 'Innenfor sesong',
    noWarnings: 'Ingen aktive farevarsler',
    matchEasy: 'Lett nok',
    matchLoop: 'Rundtur som du ønsket',
    matchView: 'Utsikt på toppen',
    matchTravel: 'innenfor reisetiden',
    matchTransport: 'Tilgjengelig med kollektiv',
    matchForest: 'Skogstur',
    matchWater: 'Ved vann',
    matchChild: 'Barnevennlig',
    advisoryShort: 'Innenfor sesong · Ingen farevarsler',
    locDenied: 'Ingen posisjon',
    or: 'eller',
    skipLocation: 'Hopp over',
    settings: 'Innstillinger',
    privacy: 'Vi lagrer ingenting om deg.',
    aboutLine1: 'Gratis. Ingen konto.',
    aboutLine2: 'Lokal-først.',
    tagsLabel: 'Hva slags tur',
    backLabel: 'Tilbake',
    closeLabel: 'Lukk',
    avoidSteep: 'Ikke bratt',
    seasonOpen: 'Åpen nå',
    seasonClosed: 'Utenfor sesong',
    moreInfo: 'Mer info',
    elevProfile: 'Høydeprofil',
    safety: 'Sikkerhet',
    safetyDetails: {
      inside_season: 'Innenfor sesong',
      no_active_warning: 'Ingen aktive farevarsler',
      weather_ok: 'Stabilt vær neste 24 t',
      not_steep: 'Ikke spesielt bratt',
      access_ok: 'Tilkomst åpen',
    },
    counties: { 'Møre og Romsdal': 'Møre og Romsdal' },
  },
  en: {
    appName: 'NærTur',
    tagline: 'One tap. A nearby hike that fits today.',
    welcomeSub: 'We pick one hike for you — based on weather, season and what you feel like today.',
    useLocation: 'Use my location',
    chooseTown: 'Choose a place',
    locationAround: 'Searching around',
    near: 'near',
    edit: 'Edit',
    filters: 'Filters',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    length: 'Length',
    under5: 'Under 5 km',
    fiveTen: '5–10 km',
    tenPlus: '10+ km',
    transport: 'Transport',
    car: 'Car',
    publicTransport: 'Public',
    walk: 'On foot',
    maxTravel: 'Max travel',
    minutes: 'min',
    preferences: 'Theme',
    avoid: 'Avoid',
    findHike: 'Find hike',
    finding: 'Finding your hike',
    findingSub: 'Checking weather, season and travel time',
    recommended: 'Recommended today',
    checkConditions: 'Check conditions',
    notRecommended: 'Not recommended now',
    distance: 'Length',
    ascent: 'Ascent',
    duration: 'Time',
    travel: 'Travel',
    whyThis: 'Why this hike',
    startHike: 'Start hike',
    anotherOne: 'Pick another',
    notMine: 'Not my hike',
    safetyNote: 'Recommended based on available data. Always check local conditions.',
    source: 'Source',
    openInMaps: 'Open in maps',
    description: 'About the hike',
    trailhead: 'Trailhead',
    parking: 'Parking',
    season: 'Season',
    monthsOpen: 'In season',
    backToResult: 'Back',
    rejectedTitle: 'Got it. Finding another.',
    rejectedSub: 'Trying a new hike based on what you said no to.',
    locating: 'Getting location',
    locOk: 'Location found',
    weatherOk: 'Good forecast',
    seasonOk: 'In season',
    noWarnings: 'No active warnings',
    matchEasy: 'Easy enough',
    matchLoop: 'Loop trail, as asked',
    matchView: 'View at the top',
    matchTravel: 'within travel time',
    matchTransport: 'Reachable by bus',
    matchForest: 'Forest walk',
    matchWater: 'By water',
    matchChild: 'Child-friendly',
    advisoryShort: 'In season · No active warnings',
    locDenied: 'No location',
    or: 'or',
    skipLocation: 'Skip',
    settings: 'Settings',
    privacy: 'We store nothing about you.',
    aboutLine1: 'Free. No account.',
    aboutLine2: 'Local-first.',
    tagsLabel: 'What kind of hike',
    backLabel: 'Back',
    closeLabel: 'Close',
    avoidSteep: 'Avoid steep',
    seasonOpen: 'Open now',
    seasonClosed: 'Out of season',
    moreInfo: 'More info',
    elevProfile: 'Elevation',
    safety: 'Safety',
    safetyDetails: {
      inside_season: 'In season',
      no_active_warning: 'No active warnings',
      weather_ok: 'Stable weather next 24 h',
      not_steep: 'Not steep',
      access_ok: 'Access open',
    },
    counties: { 'Møre og Romsdal': 'Møre og Romsdal' },
  },
};

// Tag definitions — id, NO label, EN label, icon glyph (we draw SVG)
window.TAGS = [
  { id: 'viewpoint',  no: 'Utsikt',       en: 'Viewpoint',  icon: 'view' },
  { id: 'forest',     no: 'Skog',         en: 'Forest',     icon: 'tree' },
  { id: 'mountain',   no: 'Fjell',        en: 'Mountain',   icon: 'peak' },
  { id: 'water',      no: 'Vann',         en: 'Lake',       icon: 'water' },
  { id: 'waterfall',  no: 'Foss',         en: 'Waterfall',  icon: 'falls' },
  { id: 'loop',       no: 'Rundtur',      en: 'Loop',       icon: 'loop' },
  { id: 'child',      no: 'Barnevennlig', en: 'Kid-friendly', icon: 'kid' },
  { id: 'dog',        no: 'Hund ok',      en: 'Dog ok',     icon: 'dog' },
];

// Real Møre og Romsdal hikes (simplified mock data)
window.HIKES = [
  {
    id: 'morotur-1950',
    name: 'Klimpan',
    municipality: 'Vestnes',
    difficulty: 'easy',
    distanceMeters: 2200,
    ascentMeters: 180,
    durationMinutes: 60,
    travelMinutes: 22,
    tags: ['viewpoint', 'forest', 'loop', 'child'],
    seasonMonths: [4,5,6,7,8,9,10],
    sourceUrl: 'morotur.no/tur/klimpan',
    descNo: 'Kort, fin tur opp til Klimpan med utsikt over Romsdalsfjorden. Stien går gjennom blandingsskog og er greit merket. Egnet for hele familien.',
    descEn: 'A short, fine walk up to Klimpan with views over Romsdalsfjorden. The path runs through mixed forest and is clearly marked. Suitable for the whole family.',
    matchReasons: ['easy_enough', 'loop', 'view', 'within_travel', 'forest'],
    safety: 'recommended_today',
    scene: 'fjord',
    parkingNo: 'Liten plass ved Tomrefjord',
    parkingEn: 'Small lot at Tomrefjord',
  },
  {
    id: 'morotur-2104',
    name: 'Sukkertoppen',
    municipality: 'Ålesund',
    difficulty: 'medium',
    distanceMeters: 4800,
    ascentMeters: 314,
    durationMinutes: 110,
    travelMinutes: 12,
    tags: ['viewpoint', 'mountain'],
    seasonMonths: [5,6,7,8,9,10],
    sourceUrl: 'morotur.no/tur/sukkertoppen',
    descNo: 'Det mest kjente fjellet i Ålesund. Stien starter ved Fjelltun og fortsetter bratt opp til toppen på 314 moh, med utsikt mot Sunnmørsalpene og havet.',
    descEn: 'The most famous mountain near Ålesund. The path starts at Fjelltun and climbs steeply to the summit at 314 m, with views toward the Sunnmøre Alps and the sea.',
    matchReasons: ['view', 'within_travel'],
    safety: 'recommended_today',
    scene: 'peak',
    parkingNo: 'Parkering ved Fjelltun',
    parkingEn: 'Parking at Fjelltun',
  },
  {
    id: 'morotur-1788',
    name: 'Rotsethornet',
    municipality: 'Volda',
    difficulty: 'medium',
    distanceMeters: 6200,
    ascentMeters: 659,
    durationMinutes: 180,
    travelMinutes: 38,
    tags: ['viewpoint', 'mountain', 'loop'],
    seasonMonths: [5,6,7,8,9],
    sourceUrl: 'morotur.no/tur/rotsethornet',
    descNo: 'Populær rundtur over Rotsethornet (659 moh) med vid utsikt over Voldsfjorden. Kan gås begge veier; sti og varder fra toppen og ned.',
    descEn: 'Popular loop over Rotsethornet (659 m) with wide views over Voldsfjorden. Can be walked in either direction; path and cairns from the summit.',
    matchReasons: ['loop', 'view', 'within_travel'],
    safety: 'recommended_today',
    scene: 'peak',
    parkingNo: 'Volda sentrum, sti starter ved Rotset',
    parkingEn: 'Volda centre, trail starts at Rotset',
  },
  {
    id: 'morotur-3211',
    name: 'Slogen via Patchellhytta',
    municipality: 'Ørsta',
    difficulty: 'hard',
    distanceMeters: 12400,
    ascentMeters: 1564,
    durationMinutes: 480,
    travelMinutes: 55,
    tags: ['viewpoint', 'mountain'],
    seasonMonths: [6,7,8,9],
    sourceUrl: 'morotur.no/tur/slogen',
    descNo: 'Krevende klassiker i Sunnmørsalpene. Lang dag med utsatt rygg de siste hundre meterne. Kun erfarne fjellgåere i godt vær.',
    descEn: 'A demanding classic in the Sunnmøre Alps. A long day with an exposed ridge near the top. Experienced hikers only, in good weather.',
    matchReasons: ['view'],
    safety: 'check_conditions',
    scene: 'alpine',
    parkingNo: 'Urke fergekai',
    parkingEn: 'Urke ferry quay',
  },
  {
    id: 'morotur-2440',
    name: 'Aksla',
    municipality: 'Ålesund',
    difficulty: 'easy',
    distanceMeters: 1200,
    ascentMeters: 120,
    durationMinutes: 30,
    travelMinutes: 8,
    tags: ['viewpoint', 'child'],
    seasonMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
    sourceUrl: 'morotur.no/tur/aksla',
    descNo: '418 trappetrinn opp til Fjellstua og det berømte byprospektet over Ålesund. Kort, men bratt — godt for kvelden.',
    descEn: '418 steps up to Fjellstua and the famous view over Ålesund. Short but steep — great for the evening.',
    matchReasons: ['easy_enough', 'view', 'within_travel'],
    safety: 'recommended_today',
    scene: 'town',
    parkingNo: 'Ålesund sentrum',
    parkingEn: 'Ålesund centre',
  },
];
